---
- name: Retreive secret from hvault
  hosts: "{{ vm_inventory_group }}"
  gather_facts: false

  tasks:
  - set_fact:
      pw: "{{ lookup('hashi_vault', 'secret=kv-v2/data/my-secret:password token=s.81IvMg2J0QVybI3oiSDCyAUN url=https://gcc.gov.sg:8200 validate_certs=no') }}"
      # pw: "{{ lookup('hashi_vault', 'secret=kv-v2/data/my-secret:password token=s.81IvMg2J0QVybI3oiSDCyAUN url=https://gcc.gov.sg:8200 validate_certs=no') }}"

  - debug:
      msg: "Password is {{ pw }}"
