---
- name: Retreive secret from hvault
  hosts: "{{ vm_inventory_group }}"
  gather_facts: false

  tasks:
  - set_fact:
      pw: "{{ lookup('hashi_vault', 'secret=kv-v2/data/my-secret token=s.81IvMg2J0QVybI3oiSDCyAUN url=https://gcc.gov.sg:8200 validate_certs=no') }}"

  - debug:
      msg: "Password is {{ pw['data']['password'] }}"
  
  - lineinfile:
      path: /tmp/test.txt
      regexp: '^Password: '
      line: "Password: {{ pw['data']['password'] }}"
      mode: u=rw,g=r,o=r
      create: yes
    diff: yes

  # - set_fact:
  #   pw: "{{ lookup('hashi_vault', secret='kv-v2/data/my-secret', auth_method='aws_iam_login', role_id='gvt-iam-auth-role', url='https://gcc.gov.sg:8200', mount_point='gcs-sm-ns-gvt-aws-auth', validate_certs='no') }}"
